CREATE SCHEMA "chat";
--> statement-breakpoint
CREATE SCHEMA "user";
--> statement-breakpoint
CREATE TYPE "chat"."message_type" AS ENUM('TEXT', 'IMAGE', 'FILE');--> statement-breakpoint
CREATE TYPE "user"."auth_role" AS ENUM('USER', 'ADMIN', 'LEFT');--> statement-breakpoint
CREATE TYPE "user"."auth_type" AS ENUM('NATIVE', 'SOCIAL', 'CROSS');--> statement-breakpoint
CREATE TYPE "user"."gender" AS ENUM('MALE', 'FEMALE');--> statement-breakpoint
CREATE TABLE "chat"."message" (
	"id" bigint GENERATED BY DEFAULT AS IDENTITY (sequence name "chat"."message_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"room_id" bigint NOT NULL,
	"room_member_id" bigint NOT NULL,
	"message" text,
	"message_type" "chat"."message_type" DEFAULT 'TEXT' NOT NULL,
	"is_deleted" boolean DEFAULT false NOT NULL,
	"created_at" timestamp (6) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp (6) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"deleted_at" timestamp (6) with time zone,
	CONSTRAINT "pk_message" PRIMARY KEY("id"),
	CONSTRAINT "ck_message_deleted_state" CHECK ((
        ("chat"."message"."is_deleted" IS NOT TRUE AND "chat"."message"."deleted_at" IS NULL)
        OR
        ("chat"."message"."is_deleted" IS TRUE AND "chat"."message"."deleted_at" IS NOT NULL)
      )),
	CONSTRAINT "ck_message_type" CHECK ((
        (("chat"."message"."message_type" = 'TEXT') AND ("chat"."message"."message" IS NOT NULL))
        OR
        (("chat"."message"."message_type" <> 'TEXT') AND ("chat"."message"."message" IS NULL))
      ))
);
--> statement-breakpoint
CREATE TABLE "chat"."room" (
	"id" bigint GENERATED BY DEFAULT AS IDENTITY (sequence name "chat"."room_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"is_deleted" boolean DEFAULT false NOT NULL,
	"created_at" timestamp (6) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp (6) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"deleted_at" timestamp (6) with time zone,
	CONSTRAINT "pk_room" PRIMARY KEY("id"),
	CONSTRAINT "ck_room_deleted_state" CHECK ((
        ("chat"."room"."is_deleted" IS NOT TRUE AND "chat"."room"."deleted_at" IS NULL)
        OR
        ("chat"."room"."is_deleted" IS TRUE AND "chat"."room"."deleted_at" IS NOT NULL)
      ))
);
--> statement-breakpoint
CREATE TABLE "chat"."room_member" (
	"id" bigint GENERATED BY DEFAULT AS IDENTITY (sequence name "chat"."room_member_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"room_id" bigint NOT NULL,
	"user_id" bigint NOT NULL,
	"is_accepted" boolean DEFAULT false NOT NULL,
	"last_read_message_id" bigint,
	CONSTRAINT "pk_room_member" PRIMARY KEY("id"),
	CONSTRAINT "uq_member_room_composite" UNIQUE("id","room_id"),
	CONSTRAINT "uq_user_room" UNIQUE("user_id","room_id")
);
--> statement-breakpoint
CREATE TABLE "user"."native_user" (
	"id" bigint NOT NULL,
	"password_hash" varchar(255) NOT NULL,
	CONSTRAINT "pk_native_user" PRIMARY KEY("id")
);
--> statement-breakpoint
CREATE TABLE "user"."profile_image" (
	"id" bigint GENERATED BY DEFAULT AS IDENTITY (sequence name "user"."profile_image_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"user_id" bigint NOT NULL,
	"file_name" varchar(255) NOT NULL,
	"original_name" varchar(255) NOT NULL,
	"mime_type" varchar(255) NOT NULL,
	"file_size" bigint NOT NULL,
	"is_default" boolean DEFAULT false NOT NULL,
	"created_at" timestamp (6) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT "pk_profile_image" PRIMARY KEY("id")
);
--> statement-breakpoint
CREATE TABLE "user"."refresh_token" (
	"id" bigint GENERATED BY DEFAULT AS IDENTITY (sequence name "user"."refresh_token_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"user_id" bigint NOT NULL,
	"token" varchar(255) NOT NULL,
	"expired_at" timestamp (6) with time zone NOT NULL,
	CONSTRAINT "pk_refresh_token" PRIMARY KEY("id"),
	CONSTRAINT "uq_active_refresh_token" UNIQUE("token")
);
--> statement-breakpoint
CREATE TABLE "user"."social_user" (
	"id" bigint GENERATED BY DEFAULT AS IDENTITY (sequence name "user"."social_user_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"user_id" bigint NOT NULL,
	"provider" varchar(255) NOT NULL,
	"provider_user_id" varchar(255) NOT NULL,
	CONSTRAINT "pk_social_user" PRIMARY KEY("id"),
	CONSTRAINT "uq_social_user_provider" UNIQUE("user_id","provider","provider_user_id"),
	CONSTRAINT "ck_social_provider" CHECK ("user"."social_user"."provider" IN ('GOOGLE', 'NAVER'))
);
--> statement-breakpoint
CREATE TABLE "user"."user" (
	"id" bigint GENERATED BY DEFAULT AS IDENTITY (sequence name "user"."user_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"email" varchar(255) NOT NULL,
	"nick_name" varchar(255),
	"gender" "user"."gender",
	"auth_type" "user"."auth_type" DEFAULT 'NATIVE' NOT NULL,
	"auth_role" "user"."auth_role" DEFAULT 'USER' NOT NULL,
	"created_at" timestamp (6) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp (6) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"deleted_at" timestamp (6) with time zone,
	CONSTRAINT "pk_user" PRIMARY KEY("id"),
	CONSTRAINT "ck_user_deleted_state" CHECK ((
          ("user"."user"."auth_role" <> 'LEFT' AND "user"."user"."deleted_at" IS NULL)
          OR
          ("user"."user"."auth_role" = 'LEFT' AND "user"."user"."deleted_at" IS NOT NULL)
          ))
);
--> statement-breakpoint
ALTER TABLE "chat"."message" ADD CONSTRAINT "fk_message_member_room" FOREIGN KEY ("room_member_id","room_id") REFERENCES "chat"."room_member"("id","room_id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "chat"."room_member" ADD CONSTRAINT "fk_room_member" FOREIGN KEY ("room_id") REFERENCES "chat"."room"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "chat"."room_member" ADD CONSTRAINT "fk_user_room_member" FOREIGN KEY ("user_id") REFERENCES "user"."user"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "user"."native_user" ADD CONSTRAINT "fk_native_user" FOREIGN KEY ("id") REFERENCES "user"."user"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "user"."profile_image" ADD CONSTRAINT "fk_profile_image_user" FOREIGN KEY ("user_id") REFERENCES "user"."user"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "user"."refresh_token" ADD CONSTRAINT "fk_refresh_token_user" FOREIGN KEY ("user_id") REFERENCES "user"."user"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "user"."social_user" ADD CONSTRAINT "fk_native_user" FOREIGN KEY ("user_id") REFERENCES "user"."user"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
CREATE INDEX "ix_activate_message" ON "chat"."message" USING btree ("room_id","created_at" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX "ix_deleted_message" ON "chat"."message" USING btree ("room_id","deleted_at" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX "ix_active_room_updated_at" ON "chat"."room" USING btree ("updated_at" DESC NULLS LAST) WHERE "chat"."room"."is_deleted" IS NOT TRUE;--> statement-breakpoint
CREATE INDEX "ix_delete_room_deleted_at" ON "chat"."room" USING btree ("deleted_at" DESC NULLS LAST) WHERE "chat"."room"."is_deleted" IS TRUE;--> statement-breakpoint
CREATE INDEX "ix_room_member_last_read_message" ON "chat"."room_member" USING btree ("last_read_message_id");--> statement-breakpoint
CREATE UNIQUE INDEX "uq_profile_image_default" ON "user"."profile_image" USING btree ("user_id") WHERE "user"."profile_image"."is_default" IS TRUE;--> statement-breakpoint
CREATE INDEX "ix_profile_image_user_created_at" ON "user"."profile_image" USING btree ("user_id","created_at" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX "ix_refresh_token_user" ON "user"."refresh_token" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "ix_refresh_token_expire" ON "user"."refresh_token" USING btree ("expired_at");--> statement-breakpoint
CREATE UNIQUE INDEX "uq_user_email" ON "user"."user" USING btree ("email") WHERE "user"."user"."auth_role" <> 'LEFT';--> statement-breakpoint
CREATE INDEX "ix_active_user_created_at" ON "user"."user" USING btree ("created_at" DESC NULLS LAST) WHERE "user"."user"."auth_role" <> 'LEFT';--> statement-breakpoint
CREATE INDEX "ix_delete_user_deleted_at" ON "user"."user" USING btree ("deleted_at" DESC NULLS LAST) WHERE "user"."user"."auth_role" = 'LEFT';